// ACTIONS - actionTypes.js

export const ADD_RUN = "ADD_RUN";
export const FETCH_RUNS = "FETCH_RUNS";
export const UPDATE_RUN = "UPDATE_RUN";
export const SET_SORT_ATTRIBUTE = "SET_SORT_ATTRIBUTE";
export const TOGGLE_REVERSE = "TOGGLE_REVERSE";
export const FETCH_RUNS_REQUEST = "FETCH_RUNS_REQUEST";
export const FETCH_RUNS_SUCCESS = "FETCH_RUNS_SUCCESS";
export const FETCH_RUNS_ERROR = "FETCH_RUNS_ERROR";
