// ACTIONS - actionTypes.js

export const SET_SORT_ATTRIBUTE = "SET_SORT_ATTRIBUTE";
export const TOGGLE_REVERSE = "TOGGLE_REVERSE";
export const FETCH_RUNS_REQUEST = "FETCH_RUNS_REQUEST";
export const FETCH_RUNS_SUCCESS = "FETCH_RUNS_SUCCESS";
export const FETCH_RUNS_ERROR = "FETCH_RUNS_ERROR";
export const ADD_RUN_SUCCESS = "ADD_RUN_SUCCESS";
